### PR TITLE
eject just files

### LINKED ISSUE #3: Don't include directories in shadowing component path list
of these two, only `components/bio.js` should be selectable.

```
components
components/bio.js
```

### PR DESCRIPTION
**Pull request by swyxio**
closes https://github.com/ChristopherBiscardi/gatsby-theme/issues/3

### CODE REVIEW

**Comment by swyxio** [comment]
based on https://www.npmjs.com/package/glob#options

**Review by johno — APPROVED** [review]
📁

**Comment by swyxio** [comment]
whats 📁

**Comment by johno** [comment]
Me being weird and wanting to leave an emoji with the approval 😆

**Comment by swyxio** [comment]
🐙

**Pull request closed without merging**
